### ISSUE TITLE
from model_base import ModelBase

### ISSUE THREAD

**Issue by ricomnl** [dineshresearch/Novel-Deep-Learning-Model-for-Traffic-Sign-Detection-Using-Capsule-Networks#1]
Hi,
very impressive implementation!
Could you please add the model_base module?

All the best,
Rico

**Comment by paultbr** [comment]
Hi.
Could you please add the model_base module?

**Comment by dineshresearch** [comment]
Hello,
Regarding this issue.I have added the model_base file and other required supporting files also and tested so closing this issue if you have any further queries and concerns you can contact me
